### ISSUE TITLE
multiple flakes in one image while training

### ISSUE THREAD

**Issue by rodal2** [Jaluus/2DMatGMM#3]
Hey,
thanks for creating 2DMatGMM.

I have a couple of questions regarding training the model. I have an image with multiple flakes of different thicknesses. Using the annotation tool I can select the background and select multiple flakes. Can I do that or does the training expect only one flake/thickness per image?
Also there are some flakes that have areas with multiple thickness. Should I avoid those during the training? How does the algorithm handle those cases?

Thank you very much :)

**Comment by Jaluus** [comment]
Hey Rodal,

You can have as many different thicknesses as you want, you should just define what is interesting in the image.
This means that it does not matter if your selected flakes have several different thicknesses.
But you should also only select what is interesting, so if your flake has multiple thicknesses, only select the interesting ones.
I would recommend marking only very thin flakes at first to get used to the fitting process.
Once you get used to the process you can mark thicker flakes.

If you like you can also send a picture of your multi thickness flakes, Ill have a look at them.
Also the interesting flakes should not be too small.

Best
Jan

**Comment by rodal2** [comment]
Hey Jan,
thanks for the quick reply!

I am still in the process of finding enough good thin flakes to train the algorithm with but I think I get it know, it seems promising so far :)

Best regards
